name: kelasdigital
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: 3.3.1
  cloud_firestore: 4.14.0
  cupertino_icons: ^1.0.2
  dartz: 0.10.1
  equatable: 2.0.5
  firebase_core: ^2.15.1
  firebase_messaging: 14.7.10
  flutter:
    sdk: flutter
  flutter_svg: 2.0.9
  get: ^4.6.6
  get_storage: 2.1.1
  google_fonts: ^6.1.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  http: 1.1.2
  image_picker: 1.0.6
  intl: 0.19.0
  intl_phone_number_input: 0.7.4
  introduction_screen: 3.1.12
  lottie: 3.0.0
  package_info_plus: 5.0.1
  path_provider: ^2.1.1
  persistent_bottom_nav_bar_v2: 4.2.8
  pin_code_fields: 8.0.1
  shimmer: 3.0.0
  slide_countdown: 1.5.0
  google_sign_in: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_flavorizr: 2.2.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.9
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.1

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/flags/
    - assets/images/logos/
    - assets/images/onboards/
    - assets/images/icons/
    - assets/images/icons/register/
    - assets/images/profiles/
    - assets/svgs/
    - assets/animations/
  uses-material-design: true
